theme = "amberwood"

[editor]
line-number = "relative"
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal.space]
l = ":lsp-workspace-command"

[keys.insert]
"C-c" = "normal_mode" # failsafe
